# Generated by Django 4.1.6 on 2023-06-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradas',
            options={'ordering': ['-produto'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
